services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "4000:3000"
    depends_on:
      - postgres

  postgres:
    container_name: database
    image: "postgres:12"
    expose:
      - "5432"
    env_file: ./backend/.env
    restart: always 
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:80"
volumes:
  postgres_data: